[project]
name = "projeto-popularidade-nomes-ibge"
version = "0.1.0"
description = ""
authors = [
    {name = "Jean Lucas",email = "jean.lucas.data@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests (>=2.32.5,<3.0.0)",
    "streamlit (>=1.54.0,<2.0.0)",
    "pandas (>=2.2,<3.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
